# Site settings
title: Portfolio
email: arbc139@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for totorody
baseurl:  # the subpath of your site, e.g. /blog/
url: https://arbc139.github.io # the base hostname & protocol for your site
twitter_username: 
github_username: Totorody

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/


